# Generated by Django 6.0.6 on 2026-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0003_result_resultdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
